### ISSUE TITLE
docker-py

### ISSUE THREAD

**Issue by jmatsushita** [debops/ansible-docker#1]
Hi there,

Shouldn't this also `pip install docker-py`?

Jun

**Comment by drybjed** [comment]
Currently `python-docker` is installed from Debian repositories, but I guess Jessie version (0.5.3) might be a little old. Looks like `pip install docker-py` on Jessie installs the 1.4.0 version from PyPI without issues. I'm kinda wary of using external package managers if it can be avoided, but then again, `pip` is basically a standard on DebOps hosts... I guess that role could install `docker-py` from PyPI for now but I would switch to `jessie-backports` version if it ever shows up.

Want to try a PR?

**Comment by jmatsushita** [comment]
Actually I'm not sure what was going on but pinnning the pip version of docker-py to 1.2.3 as recommended [here](https://github.com/ansible/ansible-modules-core/issues/1707) worked.

**Comment by jmatsushita** [comment]
Actually it didn't work as I guess it's conflicting with the jessie version of python-pip.

I can't reproduce unfortunately. But for now I've added `docker_api_version: 1.18` to my group_vars as I think that's the original problem. Here's the trace of the original problem for reference:

```
Traceback (most recent call last):
  File "/var/local/jun/.ansible/tmp/ansible-tmp-1443638237.11-121917321536510/docker", line 3185, in <module>
    main()
  File "/var/local/jun/.ansible/tmp/ansible-tmp-1443638237.11-121917321536510/docker", line 1542, in main
    reloaded(manager, containers, count, name)
  File "/var/local/jun/.ansible/tmp/ansible-tmp-1443638237.11-121917321536510/docker", line 1423, in reloaded
    started(manager, containers, count, name)
  File "/var/local/jun/.ansible/tmp/ansible-tmp-1443638237.11-121917321536510/docker", line 1400, in started
    created = manager.create_containers(delta)
  File "/var/local/jun/.ansible/tmp/ansible-tmp-1443638237.11-121917321536510/docker", line 1282, in create_containers
    params['host_config']['Memory'] = mem_limit
KeyError: 'host_config'
```

**Comment by drybjed** [comment]
@jmatsushita I'm not sure what you are talking about, did you try using `docker` module with this role and it fails? It might be because `python-docker` package from Jessie is installed, and `pip install docker` probably detects that and skips installation of `docker-py` package.

Try uninstalling the `python-docker` APT package, install `pip` version and check again.

**Comment by jmatsushita** [comment]
What happened is that I tried using a self made role using simple ansible docker syntax and bumped into the KeyError above. Given that it seems to be linked to docker-py I tried to install it pinned to version 1.2.3 which seemed to work but then it made debops.docker trip on Install ferment generator task with the error `ImportError: cannot import name IncompleteRead`.

Subsequent runs of the same play book failed on the docker-py install. With the same `ImportError: cannot import name IncompleteRead` error which seems to be due to incompatibilities with pip.

I removed the docker-py module manually and I'm using `docker_api_version: 1.18` now, but if I remove it the play still passes... 

Let me know if that's clearer and I'm happy to run some tests if that helps.

**Comment by drybjed** [comment]
@jmatsushita No, sorry, I think I still don't get it. What I took from your comment is, you installed `docker-py` from `pip`, and then you tried running `debops.docker` role on a host but due to conflicting version of `docker-py` and `ferment` Ansible run stopped - is that correct? I'm not sure what `docker-py` version is required by `ferment`, seems that the library should be maintained but I'm not sure. I've posted an issue in the `ferment` GitHub repository but no response as of yet. I see a possibility to fork `ferment` and maintain it in DebOps for `ferm` compatibility, but that's a long way in the future for now.

**Comment by benosman** [comment]
Firstly, DebOps is a great project, thanks @drybjed  et al ! :)

I ran into what I think is the same issue, the initial problem being that docker-py supplied by python-docker package is outdated.

Removing and purging the apt package and installing via pip actually breaks pip, which causes the error IncompleteRead when ever you run pip.

The cause of this is that docker-py requires a newer version of requests, which python-pip also has a dependency of. Pip installs the newer version of requests, but this breaks the old version of pip installed by python-pip!

So, to remedy, I had to remove python-pip, python-docker (I also did python-http2, as that was another dependency that got upgraded). Then I had to install pip (either using curl) or easy_install.

Then I installed docker-py using pip and all worked.

To get this into a playbook, I had to override the defaults apt__base_packages and docker_base_packages to remove the apt packages python-pip, python-docker, python-http2.

To get it working quickly, I didn't want to override the current roles, so I created a tiny role that took care of installing pip, and another role to install docker-py. I did however have to copy and edit the playbooks so I could call the new pip install role at the correct time (before other pip packages installed). 

Perhaps i'm missing a better way of doing that, but i'm new to DebOps, so I haven't yet found it.

**Comment by drybjed** [comment]
@benosman Hello and welcome to the project, glad you like it! :-)

DebOps is designed to be customizable using Ansible inventory. In this case, you shouldn't need to change the roles in the default install location, instead in the DebOps project directory, say in `ansible/inventory/group_vars/all/overrides.yml` you can set:

```
apt__base_packages: [ '<all packages apart from python-pip >' ]
docker_base_packages: [ '<all packages apart from python-pip >' ]
```

Basically copy the relevant variables from the role defaults and set your own (no easier way, unfortunately). This way, DebOps will not install `python-pip` packages on any hosts managed by this inventory.

There's unfortunately no way to execute your own playbooks before DebOps ones, unless you do something like:

```
debops playbooks/custom.yml ~/.local/share/debops/debops-playbooks/playbooks/site.yml -l host ...
```

This might be better in the future, if/when the scripts are updated.

On the other hand, [newer version of python-pip is in Debian Unstable](https://packages.qa.debian.org/p/python-pip.html) however it hadn't yet been migrated to Stretch. When that happens, there might be a chance for a backport to Jessie, depending on the build requirements. We will see... I very much dislike installation via `curl` and [I'm not sure about easy_install being a good solution](https://workaround.org/easy-install-debian). Backporting the Stretch `.deb` packages might be a better option in the future.

**Comment by benosman** [comment]
Thanks for the reply @drybjed.

I had overridden those defaults the way you suggested, so that's reassuring to know I did it in the correct way. :-)

I agree with your sentiments about pip being installed by curl - I was surprised that that was actually the primary suggestion on the official site. I went with easy_install as the least of two evils until a better idea presents itself.

I'm new to Debian as well as DebOps, I've been using Ubuntu server before this - part of what made me switch was to go for a stabler, less frequently updated system - I guess sometimes that is a double edged sword...

**Comment by drybjed** [comment]
This issue should be solved in the latest `debops.docker` version. The role sets up a Python `virtualenv` environment for Docker-related packages, separate from the host Python environment. Some scripts like `docker-compose` and a Python interpreter are exposed in the host environment for ease of use and Ansible module support. See the role documentation for more details.
