### ISSUE TITLE
Feature request: docker-compose

### ISSUE THREAD

**Issue by tklicki** [debops/ansible-docker#28]
I suggest adding docker-compose to this role. What do you think about this?

**Comment by drybjed** [comment]
I'm not sure how much configuration would `docker-compose` have, this role seems pretty big right now. Also, I haven't really used `docker-compose` command, not sure if it would be on each Docker host? Or could it manage stuff centrally from one host?

**Comment by tklicki** [comment]
Let's create first iteration. I suggest adding to this role docker-compose script who can manage docker containers. It could build environments after host startup or on demand.  Environments could be defined in /etc/docker/compose and when launching debops.docker role it could bring up all those docker-compose files or make sure they are running. What do you think?

**Comment by tklicki** [comment]
Let me try to create debops.docker_compose role (which makes use of debops.docker) which could do the above. You can then verify if it makes sense for you. Let's close this request for now.

**Comment by drybjed** [comment]
I've looked at the [official installation options](https://docs.docker.com/compose/install/), it doesn't look good.

The `docker-compose` package [is in Debian Stretch](https://packages.debian.org/stretch/docker-compose) so this might be a good, albeit a bit dated option later on when Stretch becomes stable.

Official Docker documentation suggests installation from GitHub via `curl` command. There's no file with any signatures in GitHub releases that I can see, so no way to check the authenticity of the binaries (seems that HashiCorp Go applications are a gold standard now). The release files have no version numbers in their names, so that would need to be tracked. Releases are not signed at all.

There's also an option to install `docker-compose` via `pip`. When I tried that it installed the binary with a bunch of Python dependencies. Unfortunately, subsequent exectution of any `pip` command results in:

```
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

It seems that the `pip install docker-compose` breaks the `pip` environment, at least on Debian Jessie.

Do you have any other suggestions about installing `docker-compose` sanely?

**Comment by tklicki** [comment]
Maybe docker_compose should be installed in separated python virtualenv ?

**Comment by tklicki** [comment]
That could be used for building whole environment and manage containers on the host.

**Comment by drybjed** [comment]
I suppose that could be an option. The `pip` Ansible module supports `virtualenv` in Ansible 2.1, I suppose that could be investigated. I don't have any experience with `virtualenv` though.

**Comment by drybjed** [comment]
@tklicki For now, you can handle `docker-compose` installation in another way, by using the [debops.resources](https://docs.debops.org/en/latest/ansible/roles/ansible-resources/docs/index.html) role. It can either download the binary directly from an URL, or you can provide it as a file from Ansible Controller. I guess it's not much, but does `debops-compose` need much more? I suppose you could even handle its configuration files that way as well, if needed.
