### ISSUE TITLE
Support extra daemon.json config for storage-driver options.

### ISSUE THREAD

**Issue by Routhinator** [debops/ansible-docker#34]
Would like to be able to get the following into daemon.json:

```
{
  "storage-driver": "devicemapper",
   "storage-opts": [
     "dm.thinpooldev=/dev/mapper/docker-thinpool",
     "dm.use_deferred_removal=true",
     "dm.use_deferred_deletion=true"
   ]
}
```

But I don't see a way to either configure the storage-driver or a var to pass extra blocks to the json file.

**Comment by drybjed** [comment]
This sounds like a neat idea. It could be implemented this way:

- convert the `daemon.json` template so that the output is stored in a variable, if it's not done already
- add a YAML dictionary variable in defaults for custom data structures included in the variable
- in the template, merge the generated configuration with custom dictionary variable

Let me know if you want to try and implement this, if not I can look at it later on.

**Comment by Routhinator** [comment]
So looking at this, I wasn't quite sure how to parse an array of unknown depth properly in Jinja, something I've not had to do yet. However adding the storage vars was quite simple to do as they were a known. I've forked and created a branch and am about to test it before submitting a pull request, which will add two vars; one for storage-driver and one for storage-options. 

I'll circle back afterwards to see how I might handle the arbitrary config blocks, I imagine we'll need to determine max depth of the array to handle it properly? Not sure.

**Comment by drybjed** [comment]
You don't need to worry about arbitrary length. Assuming that the variable contents will be YAML-formatted, all you need to do in the template is to have:
```
{% set finished_var = (template_var | combine((inventory_var | from_yaml))) %}
```
That should do it.

**Comment by Routhinator** [comment]
Hmm, ok.

Pull request #35 is in and passed my testing as working for the storage vars in the meantime.

**Comment by Routhinator** [comment]
Pull #36 is in for the arbitrary options.
